# Copyright (c) 2020, 2021, Oracle and/or its affiliates.
# Licensed under the Universal Permissive License v 1.0 as shown at https://oss.oracle.com/licenses/upl.
apiVersion: core.oam.dev/v1alpha2
kind: ApplicationConfiguration
metadata:
  name: {{ .Release.Name }}-appconf
  namespace: {{ .Release.Namespace }}
  annotations:
    version: v1.0.0
    description: "DBstat Helidon application for Verrazzano"
spec:
  components:
    - componentName: {{ .Release.Name }}-component
      traits:
        - trait:
            apiVersion: oam.verrazzano.io/v1alpha1
            kind: MetricsTrait
            spec:
                scraper: verrazzano-system/vmi-system-prometheus-0
        - trait:
            apiVersion: oam.verrazzano.io/v1alpha1
            kind: IngressTrait
            metadata:
              name: {{ .Release.Name }}-ingress
            spec:
              rules:
                - paths:
                    - path: "/"
                      pathType: Prefix
