# Copyright (c) 2020, 2021, Oracle and/or its affiliates.
# Licensed under the Universal Permissive License v 1.0 as shown at https://oss.oracle.com/licenses/upl.
apiVersion: core.oam.dev/v1alpha2
kind: Component
metadata:
  name: {{ .Release.Name }}-component
  namespace: {{ .Release.Namespace }}
spec:
  workload:
    apiVersion: oam.verrazzano.io/v1alpha1
    kind: VerrazzanoHelidonWorkload
    metadata:
      name: {{ .Release.Name }}-workload
      labels:
        app: {{ .Release.Name }}
        version: v1
    spec:
      deploymentTemplate:
        metadata:
          name: {{ .Release.Name }}-deployment
        podSpec:
          containers:
            - name: {{ .Release.Name }}-container
              image: docker.io/ilfur/helidon-dbstat
              imagePullPolicy: Always
              env:
              - name: DBUSR
                value: system
              - name: DBPWD
                valueFrom:
                  secretKeyRef:
                    name: {{ .Values.cmp.service }}cmp-db-secret
                    key: pdb_pwd
              - name: DBURL
                valueFrom:
                  configMapKeyRef:
                    name: {{ .Values.cmp.service }}cmp-db-config
                    key: pdb_conn
              ports:
                - containerPort: 8080
                  name: http
          imagePullSecrets:
            - name: dockerio
