# Default values for ords_selfservice.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

cmp:
  service: mypdb
  workload: Small
  department: Development
  comment: fresh development DB

resources: 
  limits:
    cpu: 250m
    memory: 384Mi
  requests:
    cpu: 250m
    memory: 384Mi

