apiVersion: core.oam.dev/v1alpha2
kind: ApplicationConfiguration
metadata:
  name: {{ .Release.Name }}-appconf
  namespace: {{ .Release.Namespace }}
  annotations:
    description: "python flask app config"
spec:
      components:
        - componentName: {{ .Release.Name }}-component
          traits:
            - trait:
                apiVersion: oam.verrazzano.io/v1alpha1
                kind: MetricsTrait
                spec:
                  scraper: verrazzano-system/vmi-system-prometheus-0
                  port: 5000
                  path: "/metrics"
            - trait:
                apiVersion: oam.verrazzano.io/v1alpha1
                kind: IngressTrait
                metadata:
                  name: {{ .Release.Name }}-ingress
                spec:
                  rules:
                    - paths:
                        - path: "/"
                          pathType: Prefix
            - trait:                      
                apiVersion: core.oam.dev/v1alpha2
                kind: ManualScalerTrait
                spec:
                  replicaCount: {{ .Values.containers }}



